name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # or whichever branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # (Optional) If you have a build step:
      # - name: Build your site
      #   run: |
      #     npm install
      #     npm run build

      # Upload site files to be deployed. Usually the path is either `.` (for raw HTML) 
      # or your build output folder (e.g., `dist`, `build`, etc.)
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'  # Replace with your build output if you have one

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
