name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # or whichever branch you want to trigger deployment from

permissions:
  contents: read       # Allows Actions to read repo content
  pages: write         # Allows publishing to Pages
  id-token: write      # Required for authentication with GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # (Optional) If you need a build step (e.g., for React, Hugo, Jekyll, etc.):
      # - name: Build
      #   run: |
      #     npm install
      #     npm run build

      # Upload the files you want to serve on Pages as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'  # if you built something, replace with your build output folder (e.g. 'dist' or 'build')

  deploy:
    # "needs: build" ensures the deploy job won't start until the "build" job completes successfully
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
