name: Deploy Squeeb Site to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # No build step needed if your index.html is at the repo root.
      # Just upload the entire repo root.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # The '.' means the root—where your index.html is.

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
